
OrdererOrgs:
  # ---------------------------------------------------------------------------
  # Orderer
  # ---------------------------------------------------------------------------
  - Name: Orderer
    Domain: example.com
    EnableNodeOUs: true

    # ---------------------------------------------------------------------------
    # "Specs" - See PeerOrgs below for complete description
    # ---------------------------------------------------------------------------
    Specs:
      - Hostname: orderer
        SANS:
            - "localhost"
            - "127.0.0.1"
      - Hostname: orderer2
        SANS:
          - "localhost"
          - "127.0.0.1"
      - Hostname: orderer3
        SANS:
            - "localhost"
            - "127.0.0.1"

# ---------------------------------------------------------------------------
# "PeerOrgs" - Definition of organizations managing peer nodes
# ---------------------------------------------------------------------------
PeerOrgs:
  # ---------------------------------------------------------------------------
  # Org1
  # ---------------------------------------------------------------------------
  - Name: Trans
    Domain: trans.example.com
    EnableNodeOUs: true

    Template:
      Count: 2
      # Start: 5
      # Hostname: {{.Prefix}}{{.Index}} # default
      SANS:
        - "localhost"

    Users:
      Count: 1

  - Name: Manuf
    Domain: manuf.example.com
    EnableNodeOUs: true

    Template:
      Count: 2
      # Start: 5
      # Hostname: {{.Prefix}}{{.Index}} # default
      SANS:
        - "localhost"

    Users:
      Count: 1

  - Name: Insur
    Domain: insur.example.com
    EnableNodeOUs: true

    Template:
      Count: 2
      # Start: 5
      # Hostname: {{.Prefix}}{{.Index}} # default
      SANS:
        - "localhost"

    Users:
      Count: 1

  - Name: Owner
    Domain: owner.example.com
    EnableNodeOUs: true

    Template:
      Count: 2
      # Start: 5
      # Hostname: {{.Prefix}}{{.Index}} # default
      SANS:
        - "localhost"

    Users:
      Count: 1  

  - Name: Scrap
    Domain: scrap.example.com
    EnableNodeOUs: true

    Template:
      Count: 2
      # Start: 5
      # Hostname: {{.Prefix}}{{.Index}} # default
      SANS:
        - "localhost"

    Users:
      Count: 1